name: Deploy to EC2 via SSH

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        shell: bash

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          script: |
            APP_DIR=/var/www/html
            BACKUP_DIR="${APP_DIR}_backup_$(date +'%Y%m%d_%H%M%S')"
            echo "Backup current version..."
            if [ -d "$APP_DIR" ]; then
              sudo cp -r "$APP_DIR" "$BACKUP_DIR"
            fi

            echo "Pull latest code..."
            cd "$APP_DIR"
            git reset --hard
            git clean -fd
            git pull --rebase origin main

            echo "Set permissions & restart Apache..."
            sudo chown -R apache:apache "$APP_DIR"
            sudo chmod -R 755 "$APP_DIR"
            sudo systemctl restart httpd
